spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/viewnews
    username: root
    password: root
    hikari:
      connection-timeout: '60000'
      maximum-pool-size: '5'

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: 'false'
      fail-on-empty-beans: 'false'
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} %M - %msg%n'
    org:
      hibernate:
        SQL: debug
  org:
    hibernate:
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
server:
  port: 8080
  servlet:
    context-path: /viewnews

