//Article Actions Constants

export const FIND_ARTICLE_ON_LOAD = "FIND_ARTICLE_ON_LOAD";
export const FIND_ARTICLE_ON_SEARCH = "FIND_ARTICLE_ON_SEARCH";
export const SEARCH_ARTICLE_SUCCESS = "SEARCH_ARTICLE_SUCCESS";

export const ACTIVATE_LOADING = "ACTIVATE_LOADING";
export const STOP_LOADING = "STOP_LOADING";


export const LOAD_FAVOURITE_ARTICLE = "LOAD_FAVOURITE_ARTICLE";
export const LOAD_FAVOURITE_ARTICLE_SUCCESS = "LOAD_FAVOURITE_ARTICLE_SUCCESS";
export const LOAD_FAVOURITE_ARTICLE_FAILURE = "LOAD_FAVOURITE_ARTICLE_FAILURE";

export const ADD_ARTICLE_TO_FAVOURITE = "ADD_ARTICLE_TO_FAVOURITE";
export const ADD_ARTICLE_TO_FAVOURITE_FAILURE = "ADD_ARTICLE_TO_FAVOURITE_FAILURE";
export const ADD_ARTICLE_TO_FAVOURITE_SUCCESS = "ADD_ARTICLE_TO_FAVOURITE_SUCCESS";


export const REMOVE_ARTICLE_FROM_FAVOURITE = "REMOVE_ARTICLE_FROM_FAVOURITE";
export const REMOVE_ARTICLE_FROM_FAVOURITE_SUCCESS = "REMOVE_ARTICLE_FROM_FAVOURITE_SUCCESS";
export const REMOVE_ARTICLE_FROM_FAVOURITE_FAILURE = "REMOVE_ARTICLE_FROM_FAVOURITE_FAILURE";






//User Actions Constants
export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";

export const LOG_OUT = "LOG_OUT";


export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";


export const FETCH_ROLES = "FETCH_ROLES";
export const FETCH_ROLES_FAILURE = "FETCH_ROLES_FAILURE";
export const FETCH_ROLES_SUCCESS = "FETCH_ROLES_SUCCESS";

export const FETCH_LANGUAGES = "FETCH_LANGUAGES";
export const FETCH_LANGUAGES_FAILURE = "FETCH_LANGUAGES_FAILURE";
export const FETCH_LANGUAGES_SUCCESS = "FETCH_LANGUAGES_SUCCESS";

export const CLEAR_SIGNUP= "CLEAR_SIGNUP";
